const Actions = {
  SNAPSHOT: 'SNAPSHOT',
  LOADUSERSETTINGS: 'LOADUSERSETTINGS',
  SAVECURRENTTRACKING: 'SAVECURRENTTRACKING',
  LOADCURRENTTRACKING: 'LOADCURRENTTRACKING',
  SAVEUSERSETTINGS: 'SAVEUSERSETTINGS',
  RUNTRACKING: 'RUNTRACKING',
  POSTTRACKINGS: 'POSTTRACKINGS',
  STARTTRACKING: 'STARTTRACKING',
  ISTRACKING: 'ISTRACKING'
};

export default Actions;
