const Actions = {
  SNAPSHOT: 'SNAPSHOT',
  LOADCONFIG: 'LOADCONFIG',
  SAVECURRENTTRACKING: 'SAVECURRENTTRACKING',
  LOADCURRENTTRACKING: 'LOADCURRENTTRACKING',
  SAVEUSERSETTINGS: 'SAVEUSERSETTINGS'
};

export default Actions;
